# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            psonis.com
tagline:          
url:              http://psonis.com
paginate:         1
baseurl:          /
author:
  name:           Vasileios Psonis
  url:            https://twitter.com/beijiru
  email:          no@mail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
