# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vasileios Psonis
tagline:          psonis.com
url:              psonis.com
paginate:         1
baseurl:          /
author:
  name:           Vasileios Psonis
  url:            https://twitter.com/beijiru

# Header
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/beijiru/beijiru.github.io
